/*   Messages related to the PNTCALC library.
/*
msg err1
  lan english -def
    The absolute coordinate of point "%p1s" is already set.  Error
    encountered on line %p2i of file "%p3s".
msg err2
  lan english -def
    The absolute XY coordinates of point "%p1s" are already set.  Error
    encountered on line %p2i of file "%p3s".
msg err3
  lan english -def
    The zero reference angle for point "%p1s" is already set.  Error
    encountered on line %p2i of file "%p3s".
